[package]
name = "Example2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch-irc = "4.0.0"
tokio = { version = "1", features = ["full"] }
tui = "0.18.0"
crossterm = "0.23"
